[package]
name = "subnetting-calculator"
version = "0.1.0"
edition = "2021"

[lib]
name = "subnetcalc"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
